version: '2'
services:
  proxy:
    build: ./proxy
    image: proxy
    ports:
      - "3123:3123"
    container_name: proxy
  app:
    build: ./app
    image: app
    ports:
      - "8082:8082"
    volumes:
      - "./app/static:/usr/src/app/static"
    container_name: app
    depends_on:
      -  proxy
    environment:
      - PORT=8082
